version: 2
jobs:
    test:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@latest'
            - run:
                name: Install dependencies
                command:  cd swcregistry && npm install && sudo npm install -g codecov
            - run:
                name: Test run
                command: |
                    cd swcregistry
                    npm run test
                    npm run coverage
                    codecov -t $CODECOV_TOKEN -f coverage/*.info
    build:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@latest'
            - run:
                name: Install dependencies
                command:  cd swcregistry && npm install && sudo npm install -g codecov
            - run:
                name: Test success running
                command: |
                    cd swcregistry
                    npm run test
                    npm run coverage

    publish:
        docker:
            - image: circleci/node
        steps:
            - checkout
            - run:
                name: Install dependencies
                command:  cd swcregistry && npm install
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" >> ~/.npmrc
            - run:
                name: Publish to npmjs
                command: |
                    cd swcregistry && npm run 2npm
            - run:
                name: Push changes
                command: |
                    git config --global user.email "$GIT_USER_EMAIL"
                    git config --global user.name "$GIT_USER"
                    cd swcregistry && git add . && git commit -am "Changed the package version [skip ci]" && git push -q https://${GITHUB_TOKEN}@github.com/SmartContractSecurity/SWC-registry-javascript.git master
workflows:
  version: 2
  test-and-publish:
    jobs:
      - build
      - test
      - publish:
            filters:
                branches:
                    only: master
            requires:
                - test
